using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Serialization.Generator;

// Emits a flat CSV serializer/deserializer for types whose canonical model
// contains only scalar members. Nested members never reach this backend:
// capability analysis rejects those types (SER001) before emission.
internal sealed class CsvSerializationBackend : ISerializationBackend
{
    public SerializationFormat Format => SerializationFormat.Csv;

    public void Generate(TypeDescriptor descriptor, SourceProductionContext context)
    {
        var source = Emit(descriptor);
        context.AddSource(
            $"{descriptor.TypeName}.CsvSerializer.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }

    private static string Emit(TypeDescriptor descriptor)
    {
        var indent = descriptor.Namespace.Length == 0 ? string.Empty : "    ";
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (descriptor.Namespace.Length > 0)
        {
            sb.AppendLine($"namespace {descriptor.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"{indent}public static class {descriptor.TypeName}CsvSerializer");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    private const string Header = \"{Header(descriptor)}\";");
        sb.AppendLine();
        EmitSerialize(sb, descriptor, indent);
        sb.AppendLine();
        EmitDeserialize(sb, descriptor, indent);
        sb.AppendLine();
        EmitHelpers(sb, indent);
        sb.AppendLine($"{indent}}}");

        if (descriptor.Namespace.Length > 0)
            sb.AppendLine("}");

        return sb.ToString();
    }

    private static string Header(TypeDescriptor descriptor) =>
        string.Join(",", descriptor.Members.Select(m =>
            m.Name.Replace("\\", "\\\\").Replace("\"", "\\\"")));

    private static void EmitSerialize(StringBuilder sb, TypeDescriptor descriptor, string indent)
    {
        sb.AppendLine($"{indent}    public static string Serialize({descriptor.TypeName} value)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        var sb = new System.Text.StringBuilder();");
        sb.AppendLine($"{indent}        sb.Append(Header);");
        sb.AppendLine($"{indent}        sb.Append('\\n');");

        for (var i = 0; i < descriptor.Members.Count; i++)
        {
            sb.AppendLine($"{indent}        sb.Append({AppendField(descriptor.Members[i])});");
            if (i < descriptor.Members.Count - 1)
                sb.AppendLine($"{indent}        sb.Append(',');");
        }

        sb.AppendLine($"{indent}        return sb.ToString();");
        sb.AppendLine($"{indent}    }}");
    }

    private static string AppendField(MemberDescriptor member)
    {
        var access = $"value.{member.MemberName}";
        var invariant = "System.Globalization.CultureInfo.InvariantCulture";

        return member.ScalarType switch
        {
            ScalarType.Bool => member.IsNullable
                ? $"{access}.HasValue ? ({access}.Value ? \"true\" : \"false\") : \"\""
                : $"{access} ? \"true\" : \"false\"",
            ScalarType.Int or ScalarType.Long or ScalarType.Decimal => member.IsNullable
                ? $"{access}.HasValue ? {access}.Value.ToString({invariant}) : \"\""
                : $"{access}.ToString({invariant})",
            ScalarType.Double => member.IsNullable
                ? $"{access}.HasValue ? {access}.Value.ToString(\"R\", {invariant}) : \"\""
                : $"{access}.ToString(\"R\", {invariant})",
            ScalarType.String => member.IsNullable
                ? $"{access} is null ? \"\" : EscapeField({access})"
                : $"EscapeField({access})",
            _ => throw new System.InvalidOperationException($"Member '{member.Name}' has no scalar type"),
        };
    }

    private static void EmitDeserialize(StringBuilder sb, TypeDescriptor descriptor, string indent)
    {
        var count = descriptor.Members.Count;

        sb.AppendLine($"{indent}    public static {descriptor.TypeName} Deserialize(string csv)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        var pos = 0;");
        sb.AppendLine($"{indent}        ReadRecord(csv, ref pos);");
        sb.AppendLine($"{indent}        var fields = ReadRecord(csv, ref pos);");
        sb.AppendLine($"{indent}        if (fields.Count != {count})");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            throw new System.FormatException($\"CSV row has {{fields.Count}} fields; expected {count}\");");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}        return new {descriptor.TypeName}");
        sb.AppendLine($"{indent}        {{");

        for (var i = 0; i < count; i++)
            sb.AppendLine($"{indent}            {descriptor.Members[i].MemberName} = {ParseField(descriptor.Members[i], i)},");

        sb.AppendLine($"{indent}        }};");
        sb.AppendLine($"{indent}    }}");
    }

    private static string ParseField(MemberDescriptor member, int index)
    {
        var field = $"fields[{index}]";
        var invariant = "System.Globalization.CultureInfo.InvariantCulture";

        return member.ScalarType switch
        {
            ScalarType.Bool => member.IsNullable
                ? $"{field} is null ? null : bool.Parse({field}!)"
                : $"bool.Parse({field}!)",
            ScalarType.Int => member.IsNullable
                ? $"{field} is null ? null : int.Parse({field}!, {invariant})"
                : $"int.Parse({field}!, {invariant})",
            ScalarType.Long => member.IsNullable
                ? $"{field} is null ? null : long.Parse({field}!, {invariant})"
                : $"long.Parse({field}!, {invariant})",
            ScalarType.Double => member.IsNullable
                ? $"{field} is null ? null : double.Parse({field}!, {invariant})"
                : $"double.Parse({field}!, {invariant})",
            ScalarType.Decimal => member.IsNullable
                ? $"{field} is null ? null : decimal.Parse({field}!, {invariant})"
                : $"decimal.Parse({field}!, {invariant})",
            ScalarType.String => member.IsNullable
                ? field
                : $"{field} ?? \"\"",
            _ => throw new System.InvalidOperationException($"Member '{member.Name}' has no scalar type"),
        };
    }

    private static void EmitHelpers(StringBuilder sb, string indent)
    {
        sb.AppendLine($"{indent}    private static System.Collections.Generic.List<string?> ReadRecord(string csv, ref int pos)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        var fields = new System.Collections.Generic.List<string?>();");
        sb.AppendLine($"{indent}        while (true)");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            fields.Add(ReadField(csv, ref pos));");
        sb.AppendLine($"{indent}            if (pos >= csv.Length)");
        sb.AppendLine($"{indent}                break;");
        sb.AppendLine($"{indent}            if (csv[pos] == ',')");
        sb.AppendLine($"{indent}            {{");
        sb.AppendLine($"{indent}                pos++;");
        sb.AppendLine($"{indent}                continue;");
        sb.AppendLine($"{indent}            }}");
        sb.AppendLine($"{indent}            if (csv[pos] == '\\r')");
        sb.AppendLine($"{indent}            {{");
        sb.AppendLine($"{indent}                pos++;");
        sb.AppendLine($"{indent}                if (pos < csv.Length && csv[pos] == '\\n')");
        sb.AppendLine($"{indent}                    pos++;");
        sb.AppendLine($"{indent}                break;");
        sb.AppendLine($"{indent}            }}");
        sb.AppendLine($"{indent}            if (csv[pos] == '\\n')");
        sb.AppendLine($"{indent}            {{");
        sb.AppendLine($"{indent}                pos++;");
        sb.AppendLine($"{indent}                break;");
        sb.AppendLine($"{indent}            }}");
        sb.AppendLine($"{indent}            throw new System.FormatException(\"Malformed CSV row: expected ',' or end of row\");");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}        return fields;");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}    private static string? ReadField(string csv, ref int pos)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        if (pos >= csv.Length)");
        sb.AppendLine($"{indent}            return null;");
        sb.AppendLine();
        sb.AppendLine($"{indent}        if (csv[pos] != '\"')");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            var start = pos;");
        sb.AppendLine($"{indent}            while (pos < csv.Length && csv[pos] != ',' && csv[pos] != '\\n' && csv[pos] != '\\r')");
        sb.AppendLine($"{indent}                pos++;");
        sb.AppendLine($"{indent}            var content = csv.Substring(start, pos - start);");
        sb.AppendLine($"{indent}            return content.Length == 0 ? null : content;");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}        pos++;");
        sb.AppendLine($"{indent}        var sb = new System.Text.StringBuilder();");
        sb.AppendLine($"{indent}        while (pos < csv.Length)");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            var c = csv[pos];");
        sb.AppendLine($"{indent}            if (c == '\"')");
        sb.AppendLine($"{indent}            {{");
        sb.AppendLine($"{indent}                if (pos + 1 < csv.Length && csv[pos + 1] == '\"')");
        sb.AppendLine($"{indent}                {{");
        sb.AppendLine($"{indent}                    sb.Append('\"');");
        sb.AppendLine($"{indent}                    pos += 2;");
        sb.AppendLine($"{indent}                    continue;");
        sb.AppendLine($"{indent}                }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}                pos++;");
        sb.AppendLine($"{indent}                break;");
        sb.AppendLine($"{indent}            }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}            sb.Append(c);");
        sb.AppendLine($"{indent}            pos++;");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}        return sb.ToString();");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}    private static string EscapeField(string s)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        if (s.Length == 0 || s.IndexOf(',') >= 0 || s.IndexOf('\"') >= 0 || s.IndexOf('\\n') >= 0 || s.IndexOf('\\r') >= 0)");
        sb.AppendLine($"{indent}            return \"\\\"\" + s.Replace(\"\\\"\", \"\\\"\\\"\") + \"\\\"\";");
        sb.AppendLine($"{indent}        return s;");
        sb.AppendLine($"{indent}    }}");
    }
}
