using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Serialization.Generator;

internal sealed class JsonSerializationBackend : ISerializationBackend
{
    public SerializationFormat Format => SerializationFormat.Json;

    public void Generate(TypeDescriptor descriptor, SourceProductionContext context)
    {
        context.AddSource(
            $"{descriptor.TypeName}.JsonSerializer.g.cs",
            SourceText.From(Emit(descriptor), Encoding.UTF8));
    }

    private static string Emit(TypeDescriptor descriptor)
    {
        var indent = descriptor.Namespace.Length == 0 ? string.Empty : "    ";
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (descriptor.Namespace.Length > 0)
        {
            sb.AppendLine($"namespace {descriptor.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"{indent}public static class {descriptor.TypeName}JsonSerializer");
        sb.AppendLine($"{indent}{{");
        EmitSerialize(sb, descriptor, indent);
        sb.AppendLine();
        EmitWrite(sb, descriptor, indent);
        sb.AppendLine();
        EmitDeserialize(sb, descriptor, indent);
        sb.AppendLine();
        EmitRead(sb, descriptor, indent);
        sb.AppendLine($"{indent}}}");

        if (descriptor.Namespace.Length > 0)
            sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitSerialize(StringBuilder sb, TypeDescriptor descriptor, string indent)
    {
        sb.AppendLine($"{indent}    public static string Serialize({descriptor.TypeName} value)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        using var stream = new System.IO.MemoryStream();");
        sb.AppendLine($"{indent}        using (var writer = new System.Text.Json.Utf8JsonWriter(stream))");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            Write(writer, value);");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine($"{indent}        return System.Text.Encoding.UTF8.GetString(stream.ToArray());");
        sb.AppendLine($"{indent}    }}");
    }

    private static void EmitWrite(StringBuilder sb, TypeDescriptor descriptor, string indent)
    {
        sb.AppendLine($"{indent}    internal static void Write(System.Text.Json.Utf8JsonWriter writer, {descriptor.TypeName} value)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        writer.WriteStartObject();");

        foreach (var member in descriptor.Members)
            EmitWriteMember(sb, member, indent);

        sb.AppendLine($"{indent}        writer.WriteEndObject();");
        sb.AppendLine($"{indent}    }}");
    }

    private static void EmitWriteMember(StringBuilder sb, MemberDescriptor member, string indent)
    {
        var name = Literal(member.Name);
        var access = $"value.{member.MemberName}";

        if (member.Kind == MemberKind.Nested)
        {
            if (member.IsNullable)
            {
                sb.AppendLine($"{indent}        if ({access} is null)");
                sb.AppendLine($"{indent}            writer.WriteNull({name});");
                sb.AppendLine($"{indent}        else");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            writer.WritePropertyName({name});");
                sb.AppendLine($"{indent}            {Serializer(member)}.Write(writer, {access});");
                sb.AppendLine($"{indent}        }}");
            }
            else
            {
                sb.AppendLine($"{indent}        writer.WritePropertyName({name});");
                sb.AppendLine($"{indent}        {Serializer(member)}.Write(writer, {access});");
            }
            return;
        }

        if (member.IsNullable)
        {
            sb.AppendLine($"{indent}        if ({access} is null)");
            sb.AppendLine($"{indent}            writer.WriteNull({name});");
            sb.AppendLine($"{indent}        else");
            var nonNullAccess = member.ScalarType == ScalarType.String ? access : access + ".Value";
            sb.AppendLine($"{indent}            {WriteScalar(member, name, nonNullAccess)};");
            return;
        }

        sb.AppendLine($"{indent}        {WriteScalar(member, name, access)};");
    }

    private static string WriteScalar(MemberDescriptor member, string name, string access) =>
        member.ScalarType switch
        {
            ScalarType.Bool => $"writer.WriteBoolean({name}, {access})",
            ScalarType.Int or ScalarType.Long or ScalarType.Double or ScalarType.Decimal =>
                $"writer.WriteNumber({name}, {access})",
            ScalarType.String => $"writer.WriteString({name}, {access})",
            _ => throw new System.InvalidOperationException($"Member '{member.Name}' has no scalar type"),
        };

    private static void EmitDeserialize(StringBuilder sb, TypeDescriptor descriptor, string indent)
    {
        sb.AppendLine($"{indent}    public static {descriptor.TypeName} Deserialize(string json)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        var reader = new System.Text.Json.Utf8JsonReader(System.Text.Encoding.UTF8.GetBytes(json));");
        sb.AppendLine($"{indent}        if (!reader.Read())");
        sb.AppendLine($"{indent}            throw new System.Text.Json.JsonException(\"Expected a JSON object\");");
        sb.AppendLine($"{indent}        var value = Read(ref reader);");
        sb.AppendLine($"{indent}        if (reader.Read())");
        sb.AppendLine($"{indent}            throw new System.Text.Json.JsonException(\"Unexpected content after JSON object\");");
        sb.AppendLine($"{indent}        return value;");
        sb.AppendLine($"{indent}    }}");
    }

    private static void EmitRead(StringBuilder sb, TypeDescriptor descriptor, string indent)
    {
        sb.AppendLine($"{indent}    internal static {descriptor.TypeName} Read(ref System.Text.Json.Utf8JsonReader reader)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        if (reader.TokenType != System.Text.Json.JsonTokenType.StartObject)");
        sb.AppendLine($"{indent}            throw new System.Text.Json.JsonException(\"Expected a JSON object\");");
        sb.AppendLine();

        foreach (var member in descriptor.Members)
        {
            var nullableSuffix = member.IsNullable ? "?" : string.Empty;
            sb.AppendLine($"{indent}        {member.TypeName}{nullableSuffix} {Local(member)} = default{(member.IsNullable ? string.Empty : "!")};");
        }

        sb.AppendLine();
        sb.AppendLine($"{indent}        while (reader.Read())");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            if (reader.TokenType == System.Text.Json.JsonTokenType.EndObject)");
        sb.AppendLine($"{indent}            {{");
        sb.AppendLine($"{indent}                return new {descriptor.TypeName}");
        sb.AppendLine($"{indent}                {{");
        foreach (var member in descriptor.Members)
            sb.AppendLine($"{indent}                    {member.MemberName} = {Local(member)},");
        sb.AppendLine($"{indent}                }};");
        sb.AppendLine($"{indent}            }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}            if (reader.TokenType != System.Text.Json.JsonTokenType.PropertyName)");
        sb.AppendLine($"{indent}                throw new System.Text.Json.JsonException(\"Expected a JSON property name\");");
        sb.AppendLine($"{indent}            var propertyName = reader.GetString();");
        sb.AppendLine($"{indent}            if (!reader.Read())");
        sb.AppendLine($"{indent}                throw new System.Text.Json.JsonException(\"Expected a JSON property value\");");
        sb.AppendLine();
        sb.AppendLine($"{indent}            switch (propertyName)");
        sb.AppendLine($"{indent}            {{");
        foreach (var member in descriptor.Members)
        {
            sb.AppendLine($"{indent}                case {Literal(member.Name)}:");
            sb.AppendLine($"{indent}                    {Local(member)} = {ReadValue(member)};");
            sb.AppendLine($"{indent}                    break;");
        }
        sb.AppendLine($"{indent}                default:");
        sb.AppendLine($"{indent}                    reader.Skip();");
        sb.AppendLine($"{indent}                    break;");
        sb.AppendLine($"{indent}            }}");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}        throw new System.Text.Json.JsonException(\"Incomplete JSON object\");");
        sb.AppendLine($"{indent}    }}");
    }

    private static string ReadValue(MemberDescriptor member)
    {
        if (member.Kind == MemberKind.Nested)
            return member.IsNullable
                ? $"reader.TokenType == System.Text.Json.JsonTokenType.Null ? null : {Serializer(member)}.Read(ref reader)"
                : $"{Serializer(member)}.Read(ref reader)";

        var read = member.ScalarType switch
        {
            ScalarType.Bool => "reader.GetBoolean()",
            ScalarType.Int => "reader.GetInt32()",
            ScalarType.Long => "reader.GetInt64()",
            ScalarType.Double => "reader.GetDouble()",
            ScalarType.Decimal => "reader.GetDecimal()",
            ScalarType.String => "reader.GetString()!",
            _ => throw new System.InvalidOperationException($"Member '{member.Name}' has no scalar type"),
        };

        return member.IsNullable
            ? $"reader.TokenType == System.Text.Json.JsonTokenType.Null ? null : {read}"
            : read;
    }

    private static string Serializer(MemberDescriptor member) =>
        member.TypeName + "JsonSerializer";

    private static string Local(MemberDescriptor member) =>
        "member" + member.Order.ToString(System.Globalization.CultureInfo.InvariantCulture);

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, true);
}
