// <auto-generated/>
#nullable enable

namespace Sample.Domain
{
    public static class MeasurementCsvSerializer
    {
        private const string Header = "enabled,optionalEnabled,count,optionalCount,total,optionalTotal,ratio,optionalRatio,amount,optionalAmount,label,note";

        public static string Serialize(Measurement value)
        {
            var sb = new System.Text.StringBuilder();
            sb.Append(Header);
            sb.Append('\n');
            sb.Append(value.Enabled ? "true" : "false");
            sb.Append(',');
            sb.Append(value.OptionalEnabled.HasValue ? (value.OptionalEnabled.Value ? "true" : "false") : "");
            sb.Append(',');
            sb.Append(value.Count.ToString(System.Globalization.CultureInfo.InvariantCulture));
            sb.Append(',');
            sb.Append(value.OptionalCount.HasValue ? value.OptionalCount.Value.ToString(System.Globalization.CultureInfo.InvariantCulture) : "");
            sb.Append(',');
            sb.Append(value.Total.ToString(System.Globalization.CultureInfo.InvariantCulture));
            sb.Append(',');
            sb.Append(value.OptionalTotal.HasValue ? value.OptionalTotal.Value.ToString(System.Globalization.CultureInfo.InvariantCulture) : "");
            sb.Append(',');
            sb.Append(value.Ratio.ToString("R", System.Globalization.CultureInfo.InvariantCulture));
            sb.Append(',');
            sb.Append(value.OptionalRatio.HasValue ? value.OptionalRatio.Value.ToString("R", System.Globalization.CultureInfo.InvariantCulture) : "");
            sb.Append(',');
            sb.Append(value.Amount.ToString(System.Globalization.CultureInfo.InvariantCulture));
            sb.Append(',');
            sb.Append(value.OptionalAmount.HasValue ? value.OptionalAmount.Value.ToString(System.Globalization.CultureInfo.InvariantCulture) : "");
            sb.Append(',');
            sb.Append(EscapeField(value.Label));
            sb.Append(',');
            sb.Append(value.Note is null ? "" : EscapeField(value.Note));
            return sb.ToString();
        }

        public static Measurement Deserialize(string csv)
        {
            var pos = 0;
            ReadRecord(csv, ref pos);
            var fields = ReadRecord(csv, ref pos);
            if (fields.Count != 12)
            {
                throw new System.FormatException($"CSV row has {fields.Count} fields; expected 12");
            }

            return new Measurement
            {
                Enabled = bool.Parse(fields[0]!),
                OptionalEnabled = fields[1] is null ? null : bool.Parse(fields[1]!),
                Count = int.Parse(fields[2]!, System.Globalization.CultureInfo.InvariantCulture),
                OptionalCount = fields[3] is null ? null : int.Parse(fields[3]!, System.Globalization.CultureInfo.InvariantCulture),
                Total = long.Parse(fields[4]!, System.Globalization.CultureInfo.InvariantCulture),
                OptionalTotal = fields[5] is null ? null : long.Parse(fields[5]!, System.Globalization.CultureInfo.InvariantCulture),
                Ratio = double.Parse(fields[6]!, System.Globalization.CultureInfo.InvariantCulture),
                OptionalRatio = fields[7] is null ? null : double.Parse(fields[7]!, System.Globalization.CultureInfo.InvariantCulture),
                Amount = decimal.Parse(fields[8]!, System.Globalization.CultureInfo.InvariantCulture),
                OptionalAmount = fields[9] is null ? null : decimal.Parse(fields[9]!, System.Globalization.CultureInfo.InvariantCulture),
                Label = fields[10] ?? "",
                Note = fields[11],
            };
        }

        private static System.Collections.Generic.List<string?> ReadRecord(string csv, ref int pos)
        {
            var fields = new System.Collections.Generic.List<string?>();
            while (true)
            {
                fields.Add(ReadField(csv, ref pos));
                if (pos >= csv.Length)
                    break;
                if (csv[pos] == ',')
                {
                    pos++;
                    continue;
                }
                if (csv[pos] == '\r')
                {
                    pos++;
                    if (pos < csv.Length && csv[pos] == '\n')
                        pos++;
                    break;
                }
                if (csv[pos] == '\n')
                {
                    pos++;
                    break;
                }
                throw new System.FormatException("Malformed CSV row: expected ',' or end of row");
            }

            return fields;
        }

        private static string? ReadField(string csv, ref int pos)
        {
            if (pos >= csv.Length)
                return null;

            if (csv[pos] != '"')
            {
                var start = pos;
                while (pos < csv.Length && csv[pos] != ',' && csv[pos] != '\n' && csv[pos] != '\r')
                    pos++;
                var content = csv.Substring(start, pos - start);
                return content.Length == 0 ? null : content;
            }

            pos++;
            var sb = new System.Text.StringBuilder();
            while (pos < csv.Length)
            {
                var c = csv[pos];
                if (c == '"')
                {
                    if (pos + 1 < csv.Length && csv[pos + 1] == '"')
                    {
                        sb.Append('"');
                        pos += 2;
                        continue;
                    }

                    pos++;
                    break;
                }

                sb.Append(c);
                pos++;
            }

            return sb.ToString();
        }

        private static string EscapeField(string s)
        {
            if (s.Length == 0 || s.IndexOf(',') >= 0 || s.IndexOf('"') >= 0 || s.IndexOf('\n') >= 0 || s.IndexOf('\r') >= 0)
                return "\"" + s.Replace("\"", "\"\"") + "\"";
            return s;
        }
    }
}
